
<?php
if (!defined('SERVIDOR')) define('SERVIDOR', 'localhost');
if (!defined('USUARIO')) define('USUARIO', 'root');
if (!defined('PASS')) define('PASS', '');
if (!defined('BD')) define('BD', 'cosmetologiaBD');
$servidor = "localhost";
$usuario = "root";
$pass = "";
$bd = "cosmetologiaBD";
$emailhost = "mx1.hostinger.es";
$emailusername = "support@cosmetologiagdl.fr"; 
$emailpassword = "lWL5VGdTZB";
$emailpuerto = 2727;
?>
